name: phonecat_tutorial
description: A port of the angularjs phonecat tutorial.  Each step is contained within a git branch in this repo.
dependencies:
  unittest: any
  js: any
  browser: any
  web_ui: any
